### ISSUE TITLE
splice junction usage

### ISSUE THREAD

**Issue by frankbioinfo** [gosianow/DRIMSeq_before_BioC3.6#5]
hello developer, 
thank you for this tool. this is not an issue but request your help.

Can this model be used to detect tissue specific splice junction usage across n=5 tissues? 

I have splice junction counts from star and tophat aligners for each tissue( some of the have 2 replicates and others 3replicates). 

could you please help me with model design if its possible , appreciate your help.

Many thanks.

**Comment by kvittingseerup** [comment]
Hi Frank

I think you are misunderstanding the exact purpose of DRIMSeq - it does differential usage analysis of an entire isoform - not a specific splice junction. This is an approach that computational is a bit harder but the biological interpretation is easier because you know the whole transcript.

If you are interested in specific exon usage I would suggest [DEXseq](bioconductor.org/packages/release/bioc/html/DEXSeq.html) as using all reads in the exons is more reliable than only considering junction spanning reads.

**Comment by frankbioinfo** [comment]
Hi @kvittingseerup 

Thank you for reply. I did use DEXseq, DEXseq lacks (contrast) function where i can compare it across all the tissues, hence was wondering if I can use DRIMSeq.

**Comment by kvittingseerup** [comment]
Are you sure? From section 4 of the [vignette](http://bioconductor.org/packages/release/bioc/vignettes/DEXSeq/inst/doc/DEXSeq.pdf) it looks like DEXSeq can handle complex models. 

If I was you I would ask the question on support.bioconductor.org and also describe what you have tried.
